packaging_format = 2

id = "plex"
name = "Plex Media Server"
description.en = "A media server application that combines free movies & TV with your favorite streaming services and personal media."
description.fr = "Une application de serveur multimédia qui combine des films et des émissions de télévision gratuits avec vos services de streaming préférés et vos médias personnels."

version = "1.0~ynh1"

maintainers = ["p4p4j0hn"]

[upstream]
license = "non-free"
website = "https://plex.tv"

[integration]
yunohost = ">= 11.1.14"
architectures = ["amd64", "i386", "arm64", "armhf"]
multi_instance = true
ldap = false
sso = false
# FIXME: replace with an **estimate** minimum disk and RAM requirements. e.g. 20M, 400M, 1G...
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "path"
    default = "/web"

    [install.init_main_permission]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    # This won't be saved as setting and will instead be used to initialize the SSOwat permission
    type = "group"
    default = "visitors"

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    [resources.system_user]
    # This will provision/deprovision a unix system user

    [resources.data_dir]
    # This will create/remove the data dir as /home/yunohost.app/$app
    # and store the corresponding setting $data_dir

    [resources.permissions]
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question (public=visitors, private=all_users)
    main.url = "/"

    [resources.ports]
    # This will pick a random port for reverse-proxying and store it as the $port setting
    main.default = 32400

    [resources.apt]
    # This will automatically install/uninstall the following apt packages
    # and implicitly define the $phpversion setting as 8.0 (if phpX.Y-foobar dependencies are listed)
    packages = "beignet-opencl-icd, ocl-icd-libopencl1"
    extras.plex.repo = "deb https://downloads.plex.tv/repo/deb public main"
    extras.plex.key = "https://downloads.plex.tv/plex-keys/PlexSign.key"
    extras.plex.packages = "plexmediaserver"
